config/routes.rb
Egarage::Application.routes.draw do
  root :to => 'defaults#index'  
  
  match 'hola' => 'garageSessions#new', :as => 'login'
  match 'adios' => 'garageSessions#destroy', :as => 'logout'
  match 'perfil' => 'garages#edit', :as => 'profile'
  match 'registro' => 'garages#new', :as => 'register'
  match 'mi-garaje' => 'garages#show', :as => 'my_garage'
  match 'search_dni_cliente' => 'owners#search_dni', :as => 'search_dni_cliente'
  match 'search_matricula_coche' => 'cars#search_plate', :as => 'search_matricula_coche'
  match 'search_marca_coche' => 'cars#search_plate', :as => 'search_marca_coche'
  match 'search_modelo_coche' => 'cars#search_plate', :as => 'search_modelo_coche'
  match 'add-car' => 'cars#create', :as => 'add_car'
  match 'log' =>  'history_records#index', :as => 'log_coche'
  match 'about' => 'defaults#about', :as => 'about'
  resources :garages
  resources :garage_sessions
  resources :owners
  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :car_id, :comments, :departure_date, :hours, :owner_id, :status_id, :garage_id
  belongs_to :car
  belongs_to :owner
  belongs_to :garage
  # STATUS:
  # 0 => Pendiente
  # 1 => En desarrollo
  # 2 => Terminado
  # 3 => Factura emitida
  # 4 => Factura pagada
  scope :by_garage, lambda { |garage|
      where(:garage_id => garage.id)
  }
  
  def self.estados_posibles
    [Estado.new(0, "Pendiente"),
     Estado.new(1, "En desarrollo"),
     Estado.new(2, "Terminado"),
     Estado.new(3, "Factura emitida"),
     Estado.new(4, "Fatura pagada")
    ]
  end
  
  def self.get_estado id_estado
    hash = ["Pendiente", "En desarrollo", "Terminado", "Factura emitida", "Fatura pagada"]
    hash[id_estado]
  end
  
  def self.pendientes
    where(:status_id => 0).order('created_at ASC')
  end
  
  def self.en_desarrollo
    where(:status_id => 1).order('created_at ASC')
  end
  
  def self.terminados
    where('status_id > ?',1).order('created_at ASC')
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
    @owner = Owner.find @entry.owner_id
    @car = Car.find @entry.car_id
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])
    @entry.status_id = 0
    @entry.garage_id = current_garage.id
    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%
	@car ||= Car.new
	@owner ||= Owner.new
%>
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if f.object.new_record? %>
	<div>
		<div class="field" id="busqueda-dni">
			<%= label_tag "Búsqueda de cliente por DNI" %>
			<%= text_field_tag "search[dni_cliente]", nil, :id =>"search_dni_cliente", :placeholder => 'DNI cliente', data: {autocomplete_source: search_dni_cliente_path} %>
		</div>
		<%= link_to "Nuevo cliente", "#", :id => "add-cliente"%>
	</div>
  <% end %>
	<div id="form-cliente" style="display:<%= f.object.new_record? ? "none" : "" %>">
		<fieldset>
			<h3><%= f.object.new_record? ? "Nuevo cliente" : "Cliente" %></h3>
			<div class="field">
				<%= label_tag :first_name, "Nombre*" %>
				<%= text_field_tag :first_name, @owner.first_name, :id => "owner_first_name" %>
			</div>
			<div class="field">
				<%= label_tag :last_name, "Apellidos*" %>
				<%= text_field_tag :last_name, @owner.last_name, :id => "owner_last_name" %>
			</div>
			<div class="field">
				<%= label_tag :phone, "Teléfono*" %>
				<%= text_field_tag :phone, @owner.phone, :id => "owner_phone" %>
			</div>
			<div class="field">
				<%= label_tag :mobile, "Teléfono móvil" %>
				<%= text_field_tag :mobile, @owner.mobile, :id => "owner_mobile" %>
			</div>
		</fieldset>
	</div>
	<div class="form_owner" id="busqueda-matricula">
		<%= f.hidden_field :owner_id, :value => @owner.id %>
	</div>
  <div class="field">
    <%#= f.label :owner_id %><br />
    <%#= f.number_field :owner_id %>
  </div>
<% if f.object.new_record? %>
	<div>
		<div class="field" id="busqueda-coche">
			<%= label_tag "Búsqueda de coche por matrícula" %>
			<%= text_field_tag "search[matricula_coche]", nil %>
		</div>
		<%= link_to "Nuevo coche", "#", :id => 'add-coche' %>
	</div>
  <% end %>
	<div id="form-coche" style="display:<%= f.object.new_record? ? "none" : "" %>">
		<fieldset>
			<h3><%= f.object.new_record? ? "Nuevo coche" : "Coche" %></h3>
			<div class="field">
				<%= label_tag :maker_id, "Fabricante*" %>
				<%= text_field_tag :maker_id, @car.maker.name, :id =>"search_marca_coche", :placeholder => 'Fabricante', data: {autocomplete_source: search_marca_coche_path} %>
			</div>
			<div class="field">
				<%= label_tag :modelo_id, "Modelo*" %>
				<%= text_field_tag :modelo_id, @car.modelo.model, :id =>"search_modelo_coche", :placeholder => 'Modelo', data: {autocomplete_source: search_modelo_coche_path} %>
			</div>
			<div class="field">
				<%= label_tag :year, "Año*" %>
				<%= text_field_tag :year, @car.year, :id => "search_year_coche" %>
			</div>
			<div class="field">
				<%= label_tag :mileage, "Kilometraje*" %>
				<%= text_field_tag :mileage, @car.mileage, :id => "search_km_coche" %>
			</div>
		</fieldset>
	</div>
	<div class="form_car">
		<%= f.hidden_field :car_id, :id => "add-car", :value=> @car.id%>
	</div>
  <div class="field">
    <%#= f.label :car_id %><br />
    <%#= f.number_field :car_id %>
  </div>

  <div class="field">
    <%= f.label :comments, "Observaciones" %>
    <%= f.text_area :comments %>
  </div>
  <% unless f.object.new_record? %>
  <div class="field">
    <%= f.label :status_id, "Estado de reparación" %>
    <%= f.select :status_id, options_for_select([["Pendiente",0],["En desarrollo",1],["Terminado",2],["Factura emitida",3],["Factura pagada",4]]), :selected => @entry.status_id %>
  </div>
  <div class="field">
    <%= f.label :hours, "Horas de trabajo" %>
    <%= f.number_field :hours %>
  </div>
  <div class="field">
    <%= f.label :departure_date, "Fecha de salida" %>
	<span class="sep"></span>
    <%= f.datetime_select :departure_date, use_month_numbers: true, order: [:day, :month, :year], include_blank: true %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit f.object.new_record? ? "Crear registro" : "Guardar cambios" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Actualizar registro de entrada de <%= @entry.car.public_name%></h1>

<%= render 'form' %>

<%= link_to 'Salir sin guardar', @entry %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Owner</th>
    <th>Car</th>
    <th>Status</th>
    <th>Comments</th>
    <th>Hours</th>
    <th>Departure date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.owner_id %></td>
    <td><%= entry.car_id %></td>
    <td><%= entry.status_id %></td>
    <td><%= entry.comments %></td>
    <td><%= entry.hours %></td>
    <td><%= entry.departure_date %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>Nuevo registro</h1>

<%= render 'form' %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Coche:</b>
  <%= @entry.car.public_name if @entry.car %>
</p>
<p>
  <b>Owner:</b>
  <%= link_to(@entry.owner.public_name, @entry.owner) if @entry.owner %>
</p>

<p>
  <b>Estado:</b>
  <%= Entry.get_estado(@entry.status_id) if @entry.status_id %>
</p>

<p>
  <b>Comentarios:</b>
  <%= @entry.comments %>
</p>

<p>
  <b>Horas de trabajo:</b>
  <%= @entry.hours %>
</p>
<% if @entry.departure_date %>
<p>
  <b>Departure date:</b>
  <%= @entry.departure_date.strftime('%d/%m/%Y') %>
</p>
<% end %>


<%= link_to 'Actualizar información', edit_entry_path(@entry) %> |
<%= link_to 'Retroceder', my_garage_path %>