config/routes.rb
Egarage::Application.routes.draw do
  root :to => 'defaults#index'  
  
  match 'hola' => 'garageSessions#new', :as => 'login'
  match 'adios' => 'garageSessions#destroy', :as => 'logout'
  match 'perfil' => 'garages#edit', :as => 'profile'
  match 'registro' => 'garages#new', :as => 'register'
  match 'mi-garaje' => 'garages#show', :as => 'my_garage'
  match 'search_dni_cliente' => 'owners#search_dni', :as => 'search_dni_cliente'
  match 'search_matricula_coche' => 'cars#search_plate', :as => 'search_matricula_coche'
  match 'search_marca_coche' => 'cars#search_plate', :as => 'search_marca_coche'
  match 'search_modelo_coche' => 'cars#search_plate', :as => 'search_modelo_coche'
  match 'add-car' => 'cars#create', :as => 'add_car'
  match 'log' =>  'history_records#index', :as => 'log_coche'
  match 'about' => 'defaults#about', :as => 'about'
  resources :garages
  resources :garage_sessions
  resources :owners
  resources :entries

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  attr_accessible :address, :first_name, :last_name, :mobile, :phone, :garage_id,:dni
  
  validates :first_name, :last_name, :phone, :dni, :presence => true
  
  has_many :cars
  belongs_to :garage
  
  scope :by_garage, lambda { |garage|
      where(:garage_id => garage.id)
  }
  
  
  def public_name
    return "#{last_name}, #{first_name}"
  end
  
  def get_phone
    str = phone
    if mobile?
      return "Fijo: #{str} - Móvil: #{mobile}"
    end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  set_tab :customers
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.by_garage(current_garage)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @owners }
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/new
  # GET /owners/new.json
  def new
    @owner = Owner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/1/edit
  def edit
    @owner = Owner.find(params[:id])
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(params[:owner])
    @owner.garage_id = current_garage.id
    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render json: @owner, status: :created, location: @owner }
      else
        format.html { render action: "new" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /owners/1
  # PUT /owners/1.json
  def update
    @owner = Owner.find(params[:id])

    respond_to do |format|
      if @owner.update_attributes(params[:owner])
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end
  
  def search_dni
    @clientes = Owner.by_garage(current_garage).order(:last_name).where('dni like ?', "#{params[:term]}%").limit(5)
    render json: @clientes.map{|c| {:first_name => c.first_name, 
                                    :last_name => c.last_name, 
                                    :phone => c.phone, 
                                    :mobile => c.mobile, 
                                    :label => c.public_name
                                   }
                               }
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
  def get_index_header
    return "Resultado de búsqueda" if params[:search]
    return "Mis clientes"
  end
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "Nombre*" %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
 	<%= f.label :last_name, "Apellidos*" %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :dni, "DNI*" %>
    <%= f.text_field :dni %>
  </div>

  <div class="field">
    <%= f.label :phone, "Teléfono*" %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
	<%= f.label :mobile, "Teléfono móvil" %>
    <%= f.text_field :mobile %>
  </div>

  <div class="field">
    <%= f.label :address, "Dirección" %>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editando cliente: <%= @owner.public_name%></h1>

<%= render 'form' %>

<%= link_to 'Atrás', owners_path, :class => 'boton' %>

app/views/owners/index.html.erb
<h1 class="inline"><%= get_index_header %></h1>

<%= link_to 'Nuevo cliente', new_owner_path, :class => "boton", :id => "new_owner" %>

<% @owners.each do |owner| %>
  <a class="owner-link" href="<%= owner_path owner %>">
  	<div class="owner-list">
		<span id="pn"><%= owner.public_name %></span> <span id="phone">(<%= owner.get_phone %>)</span>
  	</div>
  </a>
<% end %>

<br />

app/views/owners/new.html.erb
<h1>Nuevo cliente</h1>

<%= render 'form' %>

<%= link_to 'Atrás', owners_path, :class=>'boton' %>

app/views/owners/show.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>
<h1><%= @owner.public_name %></h1>
<div id="general-info">
	<p class="show-info">
	  <i class="fa fa-phone fa-2x"></i>
	  <span><%= @owner.phone %></span>
	</p>
	
	<p class="show-info">
	  <i class="fa fa-mobile fa-2x"></i>
	  <%= @owner.mobile %>
	</p>
	
	<p class="show-info">
	  <i class="fa fa-home fa-2x"></i>
	  <%= @owner.address %>
	</p>
	
	<% unless @owner.cars.empty? %>
		<h3>Coches en su propiedad</h3>
		<% @owner.cars.each do |car| %>
			<div class="car-item"><%= link_to car.public_name, '#' %></div>
		<% end %>
	<% end %>
</div>
<div id="menu-cars"></div>

<div class="botonera">
	<%= link_to 'Editar cliente', edit_owner_path(@owner) %> |
	<%= link_to 'Agregar coche', "#", :id => "link-add-car" %> |
	<%= link_to 'Atrás', owners_path %>
</div>