config/routes.rb
Egarage::Application.routes.draw do
  root :to => 'defaults#index'  
  
  match 'hola' => 'garageSessions#new', :as => 'login'
  match 'adios' => 'garageSessions#destroy', :as => 'logout'
  match 'perfil' => 'garages#edit', :as => 'profile'
  match 'registro' => 'garages#new', :as => 'register'
  match 'mi-garaje' => 'garages#show', :as => 'my_garage'
  match 'search_dni_cliente' => 'owners#search_dni', :as => 'search_dni_cliente'
  match 'search_matricula_coche' => 'cars#search_plate', :as => 'search_matricula_coche'
  match 'search_marca_coche' => 'cars#search_plate', :as => 'search_marca_coche'
  match 'search_modelo_coche' => 'cars#search_plate', :as => 'search_modelo_coche'
  match 'add-car' => 'cars#create', :as => 'add_car'
  match 'log' =>  'history_records#index', :as => 'log_coche'
  match 'about' => 'defaults#about', :as => 'about'
  resources :garages
  resources :garage_sessions
  resources :owners
  resources :entries

end

app/models/garage.rb
class Garage < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  attr_accessible :address, :cif, :email, :name, :phone, :avatar, :password, :password_confirmation
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  validates_confirmation_of :password
  
  has_many :owners
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  skip_before_filter :require_user, :only=>[:new, :create]
  
  # GET /garages
  # GET /garages.json
  def index
    @garages = Garage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @garages }
    end
  end

  # GET /garages/1
  # GET /garages/1.json
  def show
    set_tab :garage
    @garage = Garage.find current_garage.id
    @pendientes = Entry.pendientes
    @en_desarrollo = Entry.en_desarrollo
    @terminados = Entry.terminados

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @garage }
    end
  end

  # GET /garages/new
  # GET /garages/new.json
  def new
    @garage = Garage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @garage }
    end
  end

  # GET /garages/1/edit
  def edit
    set_tab :perfil
    @garage = Garage.find(current_garage.id)
  end

  # POST /garages
  # POST /garages.json
  def create
    @garage = Garage.new(params[:garage])

    respond_to do |format|
      if @garage.save
        format.html { redirect_to @garage, notice: 'Taller creado correctamente. ¡Bienvenido!' }
        format.json { render json: @garage, status: :created, location: @garage }
      else
        format.html { render action: "new" }
        format.json { render json: @garage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /garages/1
  # PUT /garages/1.json
  def update
    @garage = Garage.find(params[:id])

    respond_to do |format|
      if @garage.update_attributes(params[:garage])
        format.html { redirect_to profile_path, notice: 'Taller actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @garage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garages/1
  # DELETE /garages/1.json
  def destroy
    @garage = Garage.find(params[:id])
    @garage.destroy

    respond_to do |format|
      format.html { redirect_to garages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/views/garages/_form.html.erb
<%= form_for(@garage, :url => garages_path, :html => { :multipart => true }) do |f| %>
  <% if @garage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@garage.errors.count, "error") %> prohibited this garage from being saved:</h2>

      <ul>
      <% @garage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nombre del taller" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone, "Teléfono" %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email, "Correo electrónico" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
	<%= f.label :password, f.object.new_record? ? "Password" : "Cambiar password" %>
	<%= f.password_field :password %>
  </div>
  <div class="field">
	<%= f.label :password_confirmation, "Confirmar pasword" %>
	<%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :address, "Dirección" %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :cif, "CIF" %>
    <%= f.text_field :cif %>
  </div>
  <div class="field">
	<%= f.label :avatar, "Logo" %>
	<%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit f.object.new_record? ? "Registrar" : "Actualizar"%>
  </div>
<% end %>

app/views/garages/edit.html.erb
<h1>Editar perfil de <%= @garage.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @garage %> |
<%= link_to 'Back', garages_path %>

app/views/garages/index.html.erb
<h1>Listing garages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Address</th>
    <th>Cif</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @garages.each do |garage| %>
  <tr>
    <td><%= garage.name %></td>
    <td><%= garage.phone %></td>
    <td><%= garage.email %></td>
    <td><%= garage.address %></td>
    <td><%= garage.cif %></td>
    <td><%= link_to 'Show', garage %></td>
    <td><%= link_to 'Edit', edit_garage_path(garage) %></td>
    <td><%= link_to 'Destroy', garage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Garage', new_garage_path %>

app/views/garages/new.html.erb
<h1>New garage</h1>

<%= render 'form' %>

<%= link_to 'Back', garages_path %>

app/views/garages/show.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>
<h1><%= @garage.name %></h1>

<h2><i class="fa fa-flag-checkered"></i> Terminados</h2>
	<div class="trabajos">
	<% @terminados.each do |trabajo| %>
		<div class="trabajo">
			<span class="coche-desc"><%= link_to trabajo.car.public_name, trabajo %></span>
			<span class="destacado terminado"><%= Entry.get_estado trabajo.status_id %> (<%= trabajo.created_at.strftime('%d/%m/%Y')%>)</span>
		</div>
	<% end %>
	</div>
<h2><i class="fa fa-spinner fa-spin"></i> Trabajando</h2>
	<div class="trabajos">
	<% @en_desarrollo.each do |trabajo| %>
		<div class="trabajo">
			<span class="coche-desc"><%= link_to trabajo.car.public_name, trabajo %></span>
			<span class="destacado trabajando"><%= trabajo.created_at.strftime('%d/%m/%Y')%></span>
		</div>
	<% end %>
	</div>
<h2><i class="fa fa-clock-o"></i> Pendientes</h2> 
	<div class="trabajos">
	<% @pendientes.each do |trabajo| %>
		<div class="trabajo">
			<span class="coche-desc"><%= link_to trabajo.car.public_name, trabajo %></span>
			<span class="destacado pendiente"><%= trabajo.created_at.strftime('%d/%m/%Y')%></span>
		</div>
	<% end %>
	</div>